# Generated by Django 6.0.2 on 2026-03-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'picked_at', 'is_deleted'], name='candidates__status_26a22c_idx'),
        ),
    ]
