# Generated by Django 6.0.2 on 2026-03-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=15),
        ),
    ]
