# Generated by Django 6.0.2 on 2026-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_runs', '0002_batchrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='total_processed',
            field=models.IntegerField(default=0),
        ),
    ]
